name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  ARTIFACT_NAME: graalvm-gihub-actions-test.exe
jobs:
  release:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'
      - name: Build
        run: ./gradlew nativeCompile
      - name: Create archive
        working-directory: ./build/native/nativeCompile
        run: zip $ARTIFACT_NAME.zip $ARTIFACT_NAME
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/native/nativeCompile/$ARTIFACT_NAME.zip
