name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'
      - name: Build
        run: ./gradlew nativeCompile
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/native/nativeCompile/*.zip
