name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'
      - name: Build
        run: gradlew nativeCompile
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: graalvm-gihub-actions-test.exe
          path: build/native/nativeCompile/graalvm-gihub-actions-test.exe
